---

# YAML configuration file for managing collectors
# used by scheduler.py to schedule collector execution and load parameters, additional data, etc

enabled: true
# true/false boolean, toggle whether to run utility or not
exec_time: -1
# -1 == run immediately, specify execution interval in seconds
exec_duration: -1
# -1 == run indefinitely, not required for most collectors
